### ISSUE TITLE
Use a hotstring to perform an action not working

### ISSUE THREAD

**Issue by megabugman** [henrystern/hotstring_hints#1]
very useful script.
Using a hotstring to perform an actions does not to work for me,
For instance this hotstring, never shows the message box, pressing ^Space or selecting from the menu does not help.
::btw:: ;show a message box
{
    MsgBox 'You typed "btw".'
}

btw, your Example from README.md seems to be v1.1 code
::curdate:: ;send current date
    SendInput %A_MMMM% %A_DD%, %A_YYYY%
    Return

**Comment by henrystern** [comment]
Ya I couldn't think of a good way to implement this since AHK lacks an `eval()` function. 

Best I could think of was printing the hotstring code to a temporary file  and then running it with `run()` but that seemed pretty hacky (and hard to implement without major changes). 

Between that and the fact that I don't use many executable hotstrings, this feature isn't coming anytime soon.

My point in the readme is that you can put a comment on the first line and use that to remember a trigger before typing it in manually. Executing it through the menu will just send the comment but it can still be useful to, for example, look up all of your `open application` related hotstrings by typing " ;open", find the trigger you were looking for, and type it out manually.

Glad you are enjoying the script otherwise.

Henry
